### PR TITLE
Accepts multiple formats for datetime and Hasura admin secret

### LINKED ISSUE #63: Events CLI to support all timestamp forms with `--community_edition`
The Event CLI now supports the following as valid timestamp values:
- milliseconds since epoch
- ISO-8601 timestamp
- 'Now'

We should add support for all of these timestamps when the `--community_edition` flag is present.

### PR DESCRIPTION
**Pull request by ypc-faros**
Closes #63

## About
Accepts 'Now' in addition to Unix millis for time related flags (`run_start|end_time`, `deploy_start|end_time`). These will be converted to ISO-8601 format. Anything other than Unix millis or the literal 'Now' will be left unchanged (so passing a ISO-8601 is also valid).

Also adds a flag to accept the Hasura admin secret.

### CODE REVIEW

**Comment by willmarks** [comment]
Is it possible to also use your timestamp resolver for the timestamps sent to SaaS? Like [here](https://github.com/faros-ai/faros-events-cli/blob/main/faros_event.sh#L787)

**Comment by ypc-faros** [comment]
> Is it possible to also use your timestamp resolver for the timestamps sent to SaaS? Like [here](https://github.com/faros-ai/faros-events-cli/blob/main/faros_event.sh#L787)

Will do, thanks!

**Comment by ypc-faros** [comment]
> > Is it possible to also use your timestamp resolver for the timestamps sent to SaaS? Like [here](https://github.com/faros-ai/faros-events-cli/blob/main/faros_event.sh#L787)
> 
> Will do, thanks!

Want me to do that in a separate PR @willmarks?  I think this one is already doing too much (I should have separated the Hasura credential change even...)

**Comment by willmarks** [comment]
Sounds good to me!

**Review by willmarks — APPROVED** [review]

**Pull request merged**
