### PR TITLE
Process CD events mutations for CE

### PR DESCRIPTION
**Pull request by ypc-faros**
Sends Hasura mutations from CD events for Community edition

### CODE REVIEW

**Comment by willmarks** [comment]
Please update the README with the new `--community-edition` flag

**Comment by ypc-faros** [comment]
@willmarks I documented the flag in a separate PR (https://github.com/faros-ai/faros-events-cli/pull/49)

**Review by willmarks — APPROVED** [review]
Looks good!

**Comment by ypc-faros** [comment]
I added another flag `hasura_url` with a default (in response to https://github.com/faros-ai/faros-events-cli/pull/49#discussion_r814226991) cc/ @tovbinm

**Review by willmarks — COMMENTED** [review]
> I added another flag `hasura_url` with a default (in response to [#49 (comment)](https://github.com/faros-ai/faros-events-cli/pull/49#discussion_r814226991)) cc/ @tovbinm

Can we use the existing `--url` argument?

**Pull request merged**
